### ISSUE TITLE
问个很小白得问题，项目改如何启动啊

### ISSUE THREAD

**Issue by wangqilinqqq** [naihe138/naice-blog#2]

**Comment by naihe138** [comment]
这个 看readme.md 哈，需要后台node支持哦[地址](https://github.com/naihe138/naice-blog-koa)，还有管理后台[地址](https://github.com/naihe138/naice-blog-admin)

**Comment by xiamuguizhi** [comment]
@naihe138 我这小白也看不懂

**Comment by w4ctech** [comment]
> @naihe138 我这小白也看不懂

clone项目后 cd进该项目。`` npm install ``   ``npm run dev``或者和 `` yarn install ``   ``yarn run dev``
