### ISSUE TITLE
部署能不能具体出个文章

### ISSUE THREAD

**Issue by william-xue** [naihe138/naice-blog#3]

**Comment by william-xue** [comment]
build失败
![image](https://user-images.githubusercontent.com/20151622/38941367-f9e01d18-435e-11e8-8792-af7411bdd81e.png)

**Comment by naihe138** [comment]
@william-xue  这是没有问题，运行 `npm start`可以正常运行项目，但是如果你要去掉这个保存的话，在根目录建立一个`src`文件夹，在`src`文件夹建立`index.js`空文件就可以了。具体原理我也不知道是什么鬼错误。
